services:
  mongodb:
    image: mongo:6.0
    container_name: cleverum-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  websocket:
    build:
      context: ./ws
      dockerfile: Dockerfile
    container_name: cleverum-websocket
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/cleverum
    ports:
      - "3002:3002"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: cleverum-web
    restart: unless-stopped
    depends_on:
      - websocket
    environment:
      - NEXT_PUBLIC_WS_URL=ws://localhost:3002
    ports:
      - "3000:3000"

  chatbot:
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    container_name: cleverum-chatbot
    restart: unless-stopped
    depends_on:
      - web
    environment:
      - MONGO_URL=mongodb://mongodb:27017/cleverum
    ports:
      - "5000:5000"
