version: "3.8"

services:
  chatbot:
    build:
      context: .
    command: npm run start:bot
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - BOT_PORT=4000
      - OPEN_API_KEY=${OPEN_API_KEY}
      - CHATBOT_SECRET_KEY=${CHATBOT_SECRET_KEY}
      - PUBLIC_URL=${PUBLIC_URL}
      - PHONE_NUMBER=${PHONE_NUMBER}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 10s
      timeout: 10s
      retries: 5
volumes:
  mongodb_data:
