version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: cleverum-mongodb
    command: ["--wiredTigerCacheSizeGB", "0.25"] # ~256MB cache cap
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PWD}
    volumes:
      - cleverum-mongo-data:/data/db
    ports:
      - "127.0.0.1:27017:27017"
    mem_limit: 600m
    memswap_limit: 0         # prevent using swap inside container
    cpus: "0.50"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 20s
      timeout: 5s
      retries: 5

  websocket:
    build:
      context: ./websocket-server
      dockerfile: Dockerfile
    container_name: cleverum-websocket
    env_file: [ ./websocket-server/.env ]
    environment:
      - NODE_ENV=production
      - WEB_SOCKET_PORT=5000
      - PUBLIC_URL=${PUBLIC_URL}
      - WEB_SOCKET_URL=${WEB_SOCKET_URL}
    depends_on: [ mongo ]
    ports:
      - "127.0.0.1:5000:5000"   # bind to localhost
    mem_limit: 300m
    cpus: "0.30"
    restart: unless-stopped

  chatbot:
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    container_name: cleverum-chatbot
    env_file: [ ./chatbot/.env ]
    environment:
      - NODE_ENV=production
      - BOT_PORT=4000
      - OPEN_API_KEY=${OPEN_API_KEY}
      - CHATBOT_SECRET_KEY=${CHATBOT_SECRET_KEY}
      - PHONE_NUMBER=${PHONE_NUMBER}
      - MONGODB_URI=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PWD}@mongo:27017/cleverum-db?authSource=admin
    depends_on: [ mongo ]
    ports:
      - "127.0.0.1:4000:4000"   # bind to localhost
    mem_limit: 350m
    cpus: "0.35"
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: cleverum-web
    env_file: [ ./web/.env ]
    environment:
      - NODE_ENV=production
      - WEB_PORT=3000
      - WEB_SOCKET_PORT=5000
      - MONGODB_URI=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PWD}@mongo:27017/cleverum-db?authSource=admin
      - CHATBOT_INTERNAL_URL=http://chatbot:4000
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - CHATBOT_SECRET_KEY=${CHATBOT_SECRET_KEY}
      - PUBLIC_URL=${PUBLIC_URL}
      - WEB_SOCKET_URL=${WEB_SOCKET_URL}
      - DO_ENDPOINT=${DO_ENDPOINT}
      - DO_ACCESS_KEY_ID=${DO_ACCESS_KEY_ID}
      - DO_SECRET_ACCESS_KEY=${DO_SECRET_ACCESS_KEY}
      - DO_BUCKET_NAME=${DO_BUCKET_NAME}
    depends_on: [ mongo, chatbot ]
    ports:
      - "127.0.0.1:3000:3000"   # bind to localhost
    mem_limit: 900m            # leave headroom for build/other services
    cpus: "0.60"
    restart: unless-stopped

volumes:
  cleverum-mongo-data:
