version: '3.9'

services:
  # ────────────────────────────────────────────────────────────
  # MongoDB ─ root user + password  (created only the first
  # time the volume is empty).  Keep your credentials in an
  # .env file so they don’t sit in Git.
  # ────────────────────────────────────────────────────────────
  mongo:
    image: mongo:6.0
    container_name: cleverum-mongodb
    ports:
      - "27017:27017"
    volumes:
      - cleverum-mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PWD}

  # ────────────────────────────────────────────────────────────
  websocket:
    build:
      context: ./websocket-server
      dockerfile: Dockerfile
    container_name: cleverum-websocket
    restart: unless-stopped
    depends_on:
      - mongo
    env_file:
      - ./websocket-server/.env         # project-specific vars
    environment:
      - NODE_ENV=production
      - WEB_SOCKET_PORT=5000
      - PUBLIC_URL=${PUBLIC_URL}
      - WEB_SOCKET_URL=${WEB_SOCKET_URL}
    ports:
      - "5000:5000"

  # ────────────────────────────────────────────────────────────
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: cleverum-web
    restart: unless-stopped
    depends_on:
      - websocket
    env_file:
      - ./web/.env
    environment:
      - NODE_ENV=production
      - WEB_PORT=3000
      - BOT_PORT=4000
      - WEB_SOCKET_PORT=5000
      # *** Mongo connection with auth ***
      - MONGODB_URI=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PWD}@mongo:27017/${DB_NAME}?authSource=admin
      - DB_NAME=cleverum-db
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - CHATBOT_SECRET_KEY=${CHATBOT_SECRET_KEY}
      - PUBLIC_URL=${PUBLIC_URL}
      - WEB_SOCKET_URL=${WEB_SOCKET_URL}
      - DO_ENDPOINT=${DO_ENDPOINT}
      - DO_ACCESS_KEY_ID=${DO_ACCESS_KEY_ID}
      - DO_SECRET_ACCESS_KEY=${DO_SECRET_ACCESS_KEY}
      - DO_BUCKET_NAME=${DO_BUCKET_NAME}
    ports:
      - "3000:3000"

  # ────────────────────────────────────────────────────────────
  chatbot:
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    container_name: cleverum-chatbot
    restart: unless-stopped
    depends_on:
      - web
    env_file:
      - ./chatbot/.env
    environment:
      - NODE_ENV=production
      - BOT_PORT=4000
      - WEB_PORT=3000
      - WEB_SOCKET_PORT=5000
      # If the chatbot talks to Mongo, give it the same URI
      - MONGODB_URI=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PWD}@mongo:27017/${DB_NAME}?authSource=admin
      - OPEN_API_KEY=${OPEN_API_KEY}
      - CHATBOT_SECRET_KEY=${CHATBOT_SECRET_KEY}
      - PUBLIC_URL=${PUBLIC_URL}
      - PHONE_NUMBER=${PHONE_NUMBER}
    ports:
      - "4000:4000"

volumes:
  cleverum-mongo-data:
